%% Problem 1.4.b
% MATLAB script for showing that the all-ones-vector c =[ 1 1 1 1 1 1 1] is a valid codeword 

% Given a parity check matrix (H) how can one show that an arbitrary row vector
% "vec" is a valid codeword?
%   Multiplying the transpose of any valid codeword by the parity check 
%   matrix produces a zero-value.

% Lets say we are given a parity check matrix (H). 
H = [1,0,1,1,1,0,0;
     1,1,0,1,0,1,0;
     0,1,1,1,0,0,1];

% Create arbitrary row vector to determine if it's a valid codeword, i.e.
% determine if it was generated by the generator matrix (G).

c =[ 1 1 1 1 1 1 1];

% Check if the codeword is a valid codeword using the parity check matrix H
syndrome = mod(c * H', 2);  % Calculate the syndrome

% If the syndrome is all zeros, the codeword is valid
isValid = all(syndrome == 0);

if isValid
    disp('The codeword is valid.');
else
    disp('The codeword is invalid.');
end