%% Problem 4.a
% MATLAB script for showing that the all-ones-vector c =[ 1 1 1 1 1 1 1] is a valid codeword 

% Given a parity check matrix (H) how can one show that an arbitrary row vector
% "vec" is a valid codeword?
%   Multiplying the transpose of any valid codeword by the parity check 
%   matrix produces a zero-value.

% Lets say we are given a parity check matrix (H). 
H = [1,0,1,1,1,0,0;
     1,1,0,1,0,1,0;
     0,1,1,1,0,0,1];

% Create arbitrary row vector to determine if it's a valid codeword, i.e.
% determine if it was generated by the generator matrix (G).

c =[ 1 1 1 1 1 1 1];
is_valid_codeword = c * H';

if(~any(is_valid_codeword))
    disp('The codeword is valid');
else
    disp('The codeword is invalid');
end